### ISSUE TITLE
PlainTasks

### ISSUE THREAD

**Issue by fvelcker** [aziz/PlainNotes#30]
Hello,

Is there any plan to merge (or add features) from PlainTasks into PlainNotes ? (or the oppposite)

Thanks !
(great job by the way)

**Comment by fk128** [comment]
Hey,
No plans at the moment, but I guess it might happen at some point in the future.

**Comment by aziz** [comment]
I'm not planning to merge them. PlainTask is a task manager for a single file. Does not care where the file is stored.
PlainNotes is a centralized note taking tool. it manages where notes are saved and named. 

In terms of editing capabilities, I would like to add some of the Task Management features of PlainTasks to PlainNotes, but they need to be changed a little bit to fit into this new system. 
Take Archive done task for example. In PT we add them to the end of file, cause that's all we know about, while in PN I would like them to be archived somewhere centrally, so that you can look at all your archived task across multiple files and the plugin can give you some metrics and stats.
