### ISSUE TITLE
Change color does not work

### ISSUE THREAD

**Issue by cilia** [aziz/PlainNotes#31]
'Change Color' is greyed out under the 'Notes' menu, and there is no 'Notes: change color' in the command palette.

Tried uninstalling and reinstalling PlainNotes but still does not work. Anywhere to check what the problem might be?

**Comment by fk128** [comment]
Are you saving your notes with a `.note` extension? Changing colour only works with that.

**Comment by cilia** [comment]
@fk128 yes, the files have `.note` extension.

Closing existing `.note` files in Sublime, then uninstalling and re-installing PlainNotes, and finally re-saving the `.note` files using 'Save as' seem to fix the problem. Strange.

**Comment by fk128** [comment]
Does this happen every time you create a new note?

**Comment by cilia** [comment]
No, this only happened once recently after I kept Sublime running for a long time and it crashed. After the crash, the coloring disappeared for both PlainNotes and PlainTasks.

**Comment by carlosprados** [comment]
Same here with ST build 3114. I followed the instructions from cilia without luck.

**Comment by baringmo** [comment]
I'm a total newb on Sublime Text packages so I don't know the root cause of this issue, but it appears the syntax setting for the .note extension is somehow becoming corrupt.

In notes.py:NoteChangeColorCommand.is_enabled(), you can see that the 'Change Color' command will be enabled if the active window's syntax ends with "Note.tmLanguage".  Running the following command in the console shows me that my syntax is set to 'Packages/PlainNotes/Note.sublime-syntax':
`window.active_view().settings().get("syntax")`

However, if I change the syntax setting to 'Packages/PlainNotes/Note.tmLanguage' then the 'Change Color' command returns:
`window.active_view().settings().set("syntax", "Packages/PlainNotes/Note.tmLanguage")`

This is at best a work-around, as the syntax setting goes back to 'Packages/PlainNotes/Note.sublime-syntax' when a new .note file is opened.

**Comment by carlosprados** [comment]
Hello @baringmo, I made the change and updated my local copy of the `notes.py` file with your suggestion of add `window.active_view().settings().set("syntax", "Packages/PlainNotes/Note.sublime-syntax")` in an `or` sentence and now it works.

I'll observe the behavior in order to see if there are any side effect.

Thank your for the tip!

**Comment by Sonnymiranda** [comment]
@carlosprados Hey, I´m using windows, where can I find the file `notes.py`?
